from algorizer import calc, trade
from algorizer import stream_c, timeframe_c, marker_c, line_c, generatedSeries_c, candle_c, c
from algorizer import pivots_c, pivot_c
from algorizer import plot, histogram, createMarker, removeMarker, createLine, removeLine



def runCloseCandle( timeframe:timeframe_c, open, high, low, close, volume, top, bottom ):
    '''
    A candle was closed. Execute the strategy logic
    '''
    barindex = timeframe.barindex
    calc.SMA(close, 200).plot()
    calc.RSI(close, 14).plot('subpanel')


def event( stream:stream_c, event:str, param, numparams ):
    '''
    Handle events generated by the framework
    '''
    if event == "tick":
        '''
        A realtime price update was received.
        candle : a cancle_c containing the OHLCV values of the latest price.
        '''
        if not stream.running: # is backtesting
            return
        
        candle:candle_c = param

        ## Show remaining candle time and open position info on the console status line.
        ## You can remove this if you don't want it. 
        candle.updateRemainingTime()
        message = f"{stream.symbol.split(':')[0]} [{candle.remainingTimeStr()}]"
        longpos = trade.getActivePosition(c.LONG)
        if longpos:
            moreMsg = f" long:{longpos.collateral:.1f}({longpos.get_unrealized_pnl_percentage():.1f}%)"
            message += moreMsg
        shortpos = trade.getActivePosition(c.SHORT)
        if shortpos:
            moreMsg = f" short:{shortpos.collateral:.1f}({shortpos.get_unrealized_pnl_percentage():.1f}%)"
            message += moreMsg
        stream.setStatusLineMsg(message)
        return

    elif event == "broker_event":
        '''
        order_type (Buy/Sell): represented as the constants c.LONG, c.SHORT, c.TAKEPROFIT (for placing it) and c.STOPLOSS (for placing it)
        quantity (Order Quantity in Base Currency): The exact amount of the base asset (e.g., 0.01 BTC).
        quantity_dollars (Order Quantity in Dollars): The notional value of the current order in USD (e.g., if you buy 0.001 BTC at $60,000, this would be $60).
        position_type (New Position Type: Long/Short/Flat)
        position_size_base (New Position Size in Base Currency): The total quantity of the base asset currently held (signed for long/short).
        position_size_dollars (New Position Size in Dollars, Leveraged): This represents the total notional exposure of the position, including the effect of leverage.
        leverage (Leverage of the Order)
        position_collateral_dollars (Un-leveraged Capital in Position)
        '''
        if not stream.running: # is backtesting
            return
        
        order_type, quantity, quantity_dollars, position_type, position_size_base, position_size_dollars, position_collateral_dollars, leverage, price = param

        if order_type == c.TAKEPROFIT or order_type == c.STOPLOSS:
            return
        
        import requests

        # Example of an alert for my webhook 'whook': https://github.com/germangar/whook
        account = ""
        url = 'http://localhost:80/whook'
        if position_size_base == 0:
            message = f"{account} {stream.symbol} close"
        else:
            order = 'buy' if order_type == c.LONG else 'sell'
            message = f"{account} {stream.symbol} {order} {quantity_dollars:.4f}$ {leverage}x"
        if url and message:
            req = requests.post( url, data=message.encode('utf-8'), headers={'Content-Type': 'text/plain; charset=utf-8'} )
            print( f"Alert sent:  Status: {req.status_code}  Response: {req.text}" )

    elif event == "cli_command":
        '''
        Handle custom console commands.
        '''
        cmd, args = param
        if cmd == 'echo':
            print('Echo ', args)


if __name__ == '__main__':

    # configure the strategy before creating the stream
    # the backtest will happen at stream initialization
    trade.strategy.hedged = False
    trade.strategy.currency_mode = 'USD' # 'BASE' for base currency mode
    trade.strategy.order_size = 1000
    trade.strategy.max_position_size = 2000
    trade.strategy.liquidity = 10000
    trade.strategy.leverage_long = 1
    trade.strategy.leverage_short = 1
    
    stream = stream_c( 'BTC/USDT:USDT', 'binance', ['1h'], [runCloseCandle], event, 25000 )

    stream.registerPanel('subpanel', 1.0, 0.2, background_color="#313131ac" )
    stream.createWindow( '1h' )

    trade.print_summary_stats()
    trade.print_pnl_by_period_summary()

    stream.run()